# Grade Exams Based on Output File from UO_Score_OMR.R
# Jeremy Piger
# version 1.0
# Most recent version available at: https://github.com/jpiger/UO_Score

# Clear Environment and Console
rm(list = ls())
cat(rep("\n", 100))

# Load Libraries
library(stringr)
library(svDialogs)

# Set number of versions. 
# Assumption is that versions are indicated by ascending integers starting at 1, 
# and this order is maintained in the solution key file. 

num_versions=dlg_input(message="Enter the number of test versions.")
num_versions=as.numeric(num_versions$res)

if (num_versions>1) {
  version_numbers = t((1:1:num_versions))
}

dlgMessage(paste("Select .csv file that holds answer key for exam - press OK to browse for file."))$res
Answer_Key_path = file.choose() 
Answer_Key = read.csv(Answer_Key_path) # Assumes first column holds questions numbers and each subsequent column is solutions for a particular form
Answer_Key = as.data.frame(Answer_Key[,2:(num_versions+1)])

dlgMessage(paste("Select .csv file generated by UO_Score.R that holds student information and responses - press OK to browse for file."))$res
Student_Answers_path = file.choose()
Student_Answers = read.csv(Student_Answers_path) # Output file from UO_Score_OMR.R

dlgMessage(paste("Choose location and name for .csv file that will hold student scores - press OK to browse."))$res
output_file_name_path <- file.choose(new=TRUE)
output_file_name_path <- paste0(output_file_name_path,".csv")

dlgMessage(paste("Choose location and name for .txt file that will hold alerts about irregularities in student responses - press OK to browse."))$res
alert_file_name_path <- file.choose(new=TRUE)
alert_file_name_path <- paste0(alert_file_name_path,".txt")

blank_list <- list()
multiple_list <- list()

if (num_versions>1) {
  wrong_form_list = list()
  no_form_list = list()
}

# Initialize storage matrix
store_grades <- matrix(nrow=dim(Student_Answers)[1],ncol=4)

for (i in 1:dim(Student_Answers)[1]) {
  
  answers_i = t(Student_Answers[i,6:(dim(Student_Answers)[2])])
  page_number_i = Student_Answers[i,1]
  last_name_i = Student_Answers[i,2]
  first_name_i  = Student_Answers[i,3]
  sid_i = Student_Answers[i,4]

  if ("BLANK" %in% answers_i) {
    blank_answers <- which(answers_i=="BLANK")
    print_answers <- paste(blank_answers,collapse=",")
    print_name <- paste0(last_name_i,", ",first_name_i,", ",sid_i)
    print_update1 = paste0("Blank answers found for: ",print_name," (page number ", page_number_i,").")
    print_update2 = paste("Question",print_answers)
    blank_list = rbind(blank_list,print_update1)
    blank_list = rbind(blank_list,print_update2)
    blank_list = rbind(blank_list,"")
  }
  
  if (TRUE %in% (str_length(answers_i)>1)) {
    mult_answers <- which(str_length(answers_i)>1 & (answers_i!="BLANK"))
    if (length(mult_answers)>0) {
      print_answers <- paste(mult_answers,collapse=",")
      print_name <- paste0(last_name_i,", ",first_name_i,", ",sid_i)
      print_update1 = paste0("Multiple answers found for: ", print_name, " (page number ", page_number_i, ").")
      print_update2 = paste("Question",print_answers)
      multiple_list = rbind(multiple_list,print_update1)
      multiple_list = rbind(multiple_list,print_update2)
      multiple_list = rbind(multiple_list,"")
    }
  }
  
  if (num_versions==1) {
    key_form_i = as.data.frame(Answer_Key[,1])
  }

  if (num_versions>1) {
    form_i = Student_Answers[i,5]
    
    if (is.na(form_i)==FALSE) {
      key_form_i = as.data.frame(Answer_Key[,form_i])
    }
    
    if (is.na(form_i)) {
      key_form_alli = as.data.frame(Answer_Key)
      alt_scores = matrix(0,num_versions,2)
      
      for (j in 1:num_versions) {
        
        scores_alli = sum(answers_i==key_form_alli[,j])
        alt_scores[j,] = c(scores_alli,j)
        
      }
      
      max_score_i = max(alt_scores[,1])
      max_form_i = version_numbers[which.max(alt_scores[,1])]
      print_name <- paste0(last_name_i,", ",first_name_i,", ",sid_i)
      print_update1 = paste0("No version selected by ", print_name, " (page number ", page_number_i, ").")
      print_update2 = paste0("Maximum score was ",max_score_i," with version number ",max_form_i,".")
      no_form_list = rbind(no_form_list,print_update1)
      no_form_list = rbind(no_form_list,print_update2)
      no_form_list = rbind(no_form_list,"")
      
      score_i = max_score_i
      
      store_grades_i <- as.matrix(c(last_name_i, sid_i, score_i, page_number_i))
      store_grades[i,] <- t(store_grades_i)
      
      next
      
    }
    
  }
    
  score_i = sum(answers_i==key_form_i)
  
  if (num_versions>1) {
    
    if ((score_i/(dim(answers_i)[1])) < 0.5) {
        
      key_form_noti = as.data.frame(Answer_Key[,version_numbers!=form_i])
        
      alt_scores = matrix(0,(num_versions-1),2)
      alt_scores[,2] = t(version_numbers[version_numbers!=form_i])
        
      for (j in 1:(num_versions-1)) {
          
        scores_noti = sum(answers_i==key_form_noti[,j])
        alt_scores[j,1] = c(scores_noti)
          
      }
        
      if (max(alt_scores[,1])>score_i) {
        max_score_i = max(alt_scores[,1])
        max_form_i = alt_scores[which.max(alt_scores[,1]),2]
        print_name <- paste0(last_name_i,", ",first_name_i,", ",sid_i)
        print_update1 = paste0("Probable wrong version selected by ",print_name," (Page Number ",page_number_i,").")
        print_update2 = paste0("Score with selected version number ",form_i," was ",score_i,"."," Score with version number ",max_form_i," was ",max_score_i,".")
        wrong_form_list = rbind(wrong_form_list,print_update1)
        wrong_form_list = rbind(wrong_form_list,print_update2)
        wrong_form_list = rbind(wrong_form_list,"")
        
        score_i = max_score_i
        
      }
        
    }
      
  }
  
  store_grades_i <- as.matrix(c(last_name_i, sid_i, score_i, page_number_i))
  store_grades[i,] <- t(store_grades_i)
    
}

store_grade_labels <- as.matrix(c("Student", "SIS User ID", "Score", "Page Number"))
store_grades <- as.data.frame(store_grades);
names(store_grades) <- store_grade_labels
write.csv(store_grades, output_file_name_path, row.names = FALSE)

if (num_versions==1) {
  alerts_list <- rbind(blank_list,multiple_list)
  write(unlist(alerts_list),alert_file_name_path)
}

if (num_versions>1) {
  alerts_list = rbind(blank_list,multiple_list,no_form_list,wrong_form_list)
  write(unlist(alerts_list),alert_file_name_path)
}